# Minimal configuration file to run Nginx as ordinary user
# Example run /usr/bin/nginx -c nginx.user.conf

daemon off;
worker_processes 2;
events {
    use epoll;
    worker_connections 128;
}
pid /tmp/nginx_logs/nginx.pid;
error_log /tmp/nginx_logs/error.log info;

http {
    server_tokens off;
    charset utf-8;

    access_log /tmp/nginx_logs/access.log combined;
    client_body_temp_path /tmp/nginx_logs/clientbody.log;
    fastcgi_temp_path /tmp/nginx_logs/fastcgi.log;
    uwsgi_temp_path /tmp/nginx_logs/uwsgi.log;
    scgi_temp_path /tmp/nginx_logs/scgi.log;
    server {
        server_name localhost;
        listen 127.0.0.1:8080;
        location / {
            root /tmp;
            autoindex on;
            autoindex_exact_size off;
            autoindex_format html;
            autoindex_localtime on;
        }

    }

}
